env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
  - 'plugin:prettier/recommended'
parserOptions:
  ecmaVersion: 12
plugins:
  - vue
  - '@typescript-eslint'
rules:
  "@typescript-eslint/no-unused-vars": "warn"
  "@typescript-eslint/no-explicit-any": "warn"
